services:
  chat-service:
    build: .
    container_name: chat-service
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:latest
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    restart: always
    volumes:
      - mongodbdata:/data/db

volumes:
  pgdata:
  mongodbdata:
